export const vehicles = [
    {
      id: "toyota-corolla",
      name: "Toyota Corolla",
      category: "economy",
      price: 60,
      seats: 5,
      transmission: "Automatic",
      image: "/toyota.jpg?height=400&width=600",
      features: ["Air Conditioning", "Bluetooth", "USB Port", "Cruise Control"],
    },
    {
      id: "honda-civic",
      name: "Honda Civic",
      category: "economy",
      price: 65,
      seats: 5,
      transmission: "Automatic",
      image: "/Honda.jpg?height=400&width=600",
      features: ["Air Conditioning", "Bluetooth", "USB Port", "Cruise Control"],
    },
    {
      id: "ford-focus",
      name: "Ford Focus",
      category: "economy",
      price: 58,
      seats: 5,
      transmission: "Automatic",
      image: "/ford.jpg?height=400&width=600",
      features: ["Air Conditioning", "Bluetooth", "USB Port", "Cruise Control"],
    },
    {
      id: "bmw-x5",
      name: "BMW X5",
      category: "suv",
      price: 150,
      seats: 7,
      transmission: "Automatic",
      image: "/BMW.webp?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Panoramic Roof", "Premium Sound System"],
    },
    {
      id: "audi-q7",
      name: "Audi Q7",
      category: "suv",
      price: 160,
      seats: 7,
      transmission: "Automatic",
      image: "/q7.jpg?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Panoramic Roof", "Premium Sound System"],
    },
    {
      id: "range-rover-sport",
      name: "Range Rover Sport",
      category: "suv",
      price: 180,
      seats: 5,
      transmission: "Automatic",
      image: "/sport.jpg?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Panoramic Roof", "Premium Sound System"],
    },
    {
      id: "mercedes-e-class",
      name: "Mercedes E-Class",
      category: "luxury",
      price: 120,
      seats: 5,
      transmission: "Automatic",
      image: "/E-class.jpg?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Heated Seats", "Premium Sound System"],
    },
    {
      id: "audi-a6",
      name: "Audi A6",
      category: "luxury",
      price: 130,
      seats: 5,
      transmission: "Automatic",
      image: "/A6.avif?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Heated Seats", "Premium Sound System"],
    },
    {
      id: "bmw-7-series",
      name: "BMW 7 Series",
      category: "luxury",
      price: 170,
      seats: 5,
      transmission: "Automatic",
      image: "/7series.avif?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Heated Seats", "Premium Sound System"],
    },
    {
      id: "mercedes-v-class",
      name: "Mercedes V-Class",
      category: "vans",
      price: 180,
      seats: 8,
      transmission: "Automatic",
      image: "/vclass.jpg?height=400&width=600",
      features: ["Leather Seats", "Navigation", "Climate Control", "Electric Sliding Doors"],
    },
    {
      id: "vw-transporter",
      name: "VW Transporter",
      category: "vans",
      price: 140,
      seats: 9,
      transmission: "Manual",
      image: "/vw.webp?height=400&width=600",
      features: ["Spacious Interior", "Sliding Doors", "Climate Control", "Roof Rack"],
    },
  ]